# Generated by Django 3.1.6 on 2021-02-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=25)),
                ('ticker_company', models.CharField(max_length=50)),
                ('ticker_type', models.CharField(max_length=50)),
                ('ticket_exchange', models.CharField(max_length=50)),
                ('mrkt_price', models.FloatField(max_length=25)),
                ('buy_price', models.FloatField(max_length=25)),
                ('quantity', models.IntegerField(max_length=25)),
                ('bought_when', models.CharField(max_length=50)),
                ('is_sold', models.BooleanField()),
                ('sell_price', models.FloatField(max_length=25)),
                ('profit_loss', models.FloatField(max_length=25)),
                ('pl_percent', models.CharField(max_length=25)),
            ],
        ),
    ]
