# Generated by Django 3.1.6 on 2021-02-28 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="TickerModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker_symbol", models.CharField(max_length=25)),
                ("ticker_company", models.CharField(max_length=50)),
                ("ticker_exchange", models.CharField(max_length=50)),
                ("buy_price", models.FloatField(max_length=25)),
                ("buy_quantity", models.IntegerField()),
                ("bought_when", models.CharField(max_length=50)),
                (
                    "ticker_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticker_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioHistoryModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thistory_symbol", models.CharField(max_length=25)),
                ("thistory_company", models.CharField(max_length=50)),
                ("thistory_exchange", models.CharField(max_length=50)),
                ("thistory_bprice", models.FloatField(max_length=25)),
                ("thistory_squantity", models.IntegerField()),
                ("thistory_bwhen", models.CharField(max_length=50)),
                ("thistory_swhen", models.CharField(max_length=50)),
                ("thistory_sprice", models.FloatField(max_length=25)),
                ("thistory_closepl", models.FloatField()),
                ("thistory_plper", models.FloatField()),
                ("thistory_pcolor", models.CharField(max_length=25)),
                (
                    "thistory_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thistory_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
