# Generated by Django 3.1.6 on 2021-02-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickermodel',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
