# Generated by Django 3.1.6 on 2021-03-01 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("portfoliowebsite", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="portfoliohistorymodel",
            old_name="thistory_closepl",
            new_name="thistory_overallpl",
        )
    ]
