# Generated by Django 3.1.6 on 2021-02-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("portfoliowebsite", "0002_auto_20210213_1844")]

    operations = [
        migrations.RenameField(
            model_name="tickermodel",
            old_name="ticket_exchange",
            new_name="ticker_exchange",
        ),
        migrations.RenameField(
            model_name="tickermodel", old_name="ticker", new_name="ticker_symbol"
        ),
        migrations.RemoveField(model_name="tickermodel", name="is_sold"),
        migrations.RemoveField(model_name="tickermodel", name="mrkt_price"),
        migrations.RemoveField(model_name="tickermodel", name="pl_percent"),
        migrations.RemoveField(model_name="tickermodel", name="profit_loss"),
        migrations.RemoveField(model_name="tickermodel", name="sell_price"),
        migrations.RemoveField(model_name="tickermodel", name="ticker_type"),
    ]
