# Generated by Django 3.1.6 on 2021-02-25 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portfoliowebsite", "0002_auto_20210222_0528"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioHistoryModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thistory_symbol", models.CharField(max_length=25)),
                ("thistory_company", models.CharField(max_length=50)),
                ("thistory_bprice", models.FloatField(max_length=25)),
                ("thistory_bquantity", models.IntegerField()),
                ("thistory_bwhen", models.CharField(max_length=50)),
                ("thistory_swhen", models.CharField(max_length=50)),
                ("close_pl", models.FloatField()),
                (
                    "thistory_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thistory_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
