# Generated by Django 3.1.6 on 2021-02-18 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("portfoliowebsite", "0003_auto_20210218_0034")]

    operations = [
        migrations.RenameField(
            model_name="tickermodel", old_name="quantity", new_name="buy_quantity"
        )
    ]
